
module.exports = {

	USER_ROLE: {
		'ADVISOR':'ADVISOR',
		'CLIENT':'CLIENT',
		'ADMINISTRATOR':'ADMINISTRATOR'
	},

	ROUTE_ACCESS:{
		'ANNONIMOUS':['CLIENT','ADVISOR','CLIENT_ADVISOR','ADMINISTRATOR'],
		'CLIENT':['CLIENT','CLIENT_ADVISOR','ADMINISTRATOR'],
		'ADMINISTRATOR':['ADMINISTRATOR'],
		'ADVISOR':['ADVISOR','CLIENT_ADVISOR','ADMINISTRATOR'],
		'CLIENT_ADVISOR':['CLIENT_ADVISOR','ADMINISTRATOR']
	},
	AUTH_HEADER: 'Authorization'
}